In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# **Import Libraries**

In [2]:
import pandas as pd
import xlrd

# **Load dataset into dataframe**

In [3]:
df = pd.read_csv('/content/drive/MyDrive/UIT-Learning/TERM6/OLAP/ĐỒ ÁN OLAP/Dataset/Smart Supply Chain/Processed Data/utf8.csv', sep=';', encoding="utf-8", decimal=",")

In [4]:
pd.set_option('display.max_columns', 38)

In [5]:
df.head(2)

,Order Id,Type,Days for shipping (real),Days for shipment (scheduled),Customer Id,Customer City,Customer Country,Customer Fname,Customer Lname,Customer Segment,Customer State,Customer Street,Department Name,Market,Order Region,Order State,Order City,Order Country,order date (DateOrders),Order Item Cardprod Id,Category Name,Product Name,Order Item Product Price,Order Item Discount,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Status,shipping date (DateOrders),Shipping Mode
0,1,CASH,2,4,11599,Hickory,EE. UU.,Mary,Malone,Consumer,NC,8708 Indian Horse Highway,Fan Shop,LATAM,Central America,Distrito Federal,Mexico City,México,1/1/2015 0:00,957,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.980011,60.0,1,299.980011,239.979996,88.790001,CLOSED,1/3/2015 0:00,Standard Class
1,4,CASH,5,4,8827,San Antonio,EE. UU.,Brian,Wilson,Home Office,TX,8396 High Corners,Outdoors,LATAM,South America,Risaralda,Dos Quebradas,Colombia,1/1/2015 1:03,897,Accessories,Team Golf New England Patriots Putter Grip,24.990000,9.0,2,49.980000,40.980000,4.100000,CLOSED,1/6/2015 1:03,Standard Class

# **Rename Columns**

In [6]:
df.rename(columns={'Order Id':'Order_ID'}, inplace=True)
df.rename(columns={'Type':'Payment_Method'}, inplace=True)
df.rename(columns={'Days for shipping (real)':'Real_Days_Shipping'}, inplace=True)
df.rename(columns={'Days for shipment (scheduled)':'Scheduled_Days_Shipping'}, inplace=True)
df.rename(columns={'Customer Id':'Customer_ID'}, inplace=True)
df.rename(columns={'Customer City':'Customer_City'}, inplace=True)
df.rename(columns={'Customer Country':'Customer_Country'}, inplace=True)
df.rename(columns={'Customer Fname':'Customer_Fname'}, inplace=True)
df.rename(columns={'Customer Lname':'Customer_Lname'}, inplace=True)
df.rename(columns={'Customer Segment':'Customer_Segment'}, inplace=True)
df.rename(columns={'Customer State':'Customer_State'}, inplace=True)
df.rename(columns={'Customer Street':'Customer_Street'}, inplace=True)
df.rename(columns={'Department Name':'Department_Name'}, inplace=True)
df.rename(columns={'Market':'Order_Market'}, inplace=True)
df.rename(columns={'Order Region':'Order_Region'}, inplace=True)
df.rename(columns={'Order State':'Order_State'}, inplace=True)
df.rename(columns={'Order City':'Order_City'}, inplace=True)
df.rename(columns={'Order Country':'Order_Country'}, inplace=True)
df.rename(columns={'order date (DateOrders)':'Order_Date'}, inplace=True)
df.rename(columns={'Order Item Cardprod Id':'Item_ID'}, inplace=True)
df.rename(columns={'Category Name':'Category_Name'}, inplace=True)
df.rename(columns={'Product Name':'Item_Name'}, inplace=True)
df.rename(columns={'Order Item Product Price':'Item_Price'}, inplace=True)
df.rename(columns={'Order Item Discount':'Item_Discount'}, inplace=True)
df.rename(columns={'Order Item Quantity':'Quantity'}, inplace=True)
df.rename(columns={'Sales':'Estimate_Value'}, inplace=True)
df.rename(columns={'Order Item Total':'Real_Value'}, inplace=True)
df.rename(columns={'Order Profit Per Order':'Order_Profit'}, inplace=True)
df.rename(columns={'Order Status':'Order_Status'}, inplace=True)
df.rename(columns={'shipping date (DateOrders)':'Shipping_Date'}, inplace=True)
df.rename(columns={'Shipping Mode':'Shipping_Mode'}, inplace=True)

# **Change Datetimes type**

In [7]:
df['Shipping_Date'] = pd.to_datetime(df['Shipping_Date'], format='%m/%d/%Y %H:%M')
df['Shipping_Date'] = df['Shipping_Date'].dt.strftime('%d-%m-%Y')

In [8]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='%m/%d/%Y %H:%M')
df['Order_Date'] = df['Order_Date'].dt.strftime('%d-%m-%Y')

In [9]:
df['Shipment_ID'] = df.apply(lambda row: row['Order_ID'], axis=1)
df.head()

,Order_ID,Payment_Method,Real_Days_Shipping,Scheduled_Days_Shipping,Customer_ID,Customer_City,Customer_Country,Customer_Fname,Customer_Lname,Customer_Segment,Customer_State,Customer_Street,Department_Name,Order_Market,Order_Region,Order_State,Order_City,Order_Country,Order_Date,Item_ID,Category_Name,Item_Name,Item_Price,Item_Discount,Quantity,Estimate_Value,Real_Value,Order_Profit,Order_Status,Shipping_Date,Shipping_Mode,Shipment_ID
0,1,CASH,2,4,11599,Hickory,EE. UU.,Mary,Malone,Consumer,NC,8708 Indian Horse Highway,Fan Shop,LATAM,Central America,Distrito Federal,Mexico City,México,01-01-2015,957,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.980011,60.000000,1,299.980011,239.979996,88.790001,CLOSED,03-01-2015,Standard Class,1
1,4,CASH,5,4,8827,San Antonio,EE. UU.,Brian,Wilson,Home Office,TX,8396 High Corners,Outdoors,LATAM,South America,Risaralda,Dos Quebradas,Colombia,01-01-2015,897,Accessories,Team Golf New England Patriots Putter Grip,24.990000,9.000000,2,49.980000,40.980000,4.100000,CLOSED,06-01-2015,Standard Class,4
2,5,DEBIT,6,4,11318,Caguas,Puerto Rico,Mary,Henry,Consumer,PR,3047 Silent Embers Maze,Apparel,LATAM,South America,Risaralda,Dos Quebradas,Colombia,01-01-2015,403,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.990005,20.799999,1,129.990005,109.190002,34.939999,COMPLETE,07-01-2015,Standard Class,5
3,5,DEBIT,6,4,11318,Caguas,Puerto Rico,Mary,Henry,Consumer,PR,3047 Silent Embers Maze,Fan Shop,LATAM,South America,Risaralda,Dos Quebradas,Colombia,01-01-2015,957,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.980011,51.000000,1,299.980011,248.979996,109.550003,COMPLETE,07-01-2015,Standard Class,5
4,5,DEBIT,6,4,11318,Caguas,Puerto Rico,Mary,Henry,Consumer,PR,3047 Silent Embers Maze,Fan Shop,LATAM,South America,Risaralda,Dos Quebradas,Colombia,01-01-2015,957,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.980011,54.000000,1,299.980011,245.979996,92.239998,COMPLETE,07-01-2015,Standard Class,5

# **Add Shipment ID**

In [10]:
cols = ['Order_ID',
  'Shipment_ID',
 'Payment_Method',
 'Real_Days_Shipping',
 'Scheduled_Days_Shipping',
 'Customer_ID',
 'Customer_City',
 'Customer_Country',
 'Customer_Fname',
 'Customer_Lname',
 'Customer_Segment',
 'Customer_State',
 'Customer_Street',
 'Department_Name',
 'Order_Market',
 'Order_Region',
 'Order_State',
 'Order_City',
 'Order_Country',
 'Order_Date',
 'Item_ID',
 'Category_Name',
 'Item_Name',
 'Item_Price',
 'Item_Discount',
 'Quantity',
 'Estimate_Value',
 'Real_Value',
 'Order_Profit',
 'Order_Status',
 'Shipping_Date',
 'Shipping_Mode']

df = df[cols]

# **Modify Order ID**

In [11]:
df['Order_ID'] = df.index.to_list()
df.head()

,Order_ID,Shipment_ID,Payment_Method,Real_Days_Shipping,Scheduled_Days_Shipping,Customer_ID,Customer_City,Customer_Country,Customer_Fname,Customer_Lname,Customer_Segment,Customer_State,Customer_Street,Department_Name,Order_Market,Order_Region,Order_State,Order_City,Order_Country,Order_Date,Item_ID,Category_Name,Item_Name,Item_Price,Item_Discount,Quantity,Estimate_Value,Real_Value,Order_Profit,Order_Status,Shipping_Date,Shipping_Mode
0,0,1,CASH,2,4,11599,Hickory,EE. UU.,Mary,Malone,Consumer,NC,8708 Indian Horse Highway,Fan Shop,LATAM,Central America,Distrito Federal,Mexico City,México,01-01-2015,957,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.980011,60.000000,1,299.980011,239.979996,88.790001,CLOSED,03-01-2015,Standard Class
1,1,4,CASH,5,4,8827,San Antonio,EE. UU.,Brian,Wilson,Home Office,TX,8396 High Corners,Outdoors,LATAM,South America,Risaralda,Dos Quebradas,Colombia,01-01-2015,897,Accessories,Team Golf New England Patriots Putter Grip,24.990000,9.000000,2,49.980000,40.980000,4.100000,CLOSED,06-01-2015,Standard Class
2,2,5,DEBIT,6,4,11318,Caguas,Puerto Rico,Mary,Henry,Consumer,PR,3047 Silent Embers Maze,Apparel,LATAM,South America,Risaralda,Dos Quebradas,Colombia,01-01-2015,403,Men's Footwear,Nike Men's CJ Elite 2 TD Football Cleat,129.990005,20.799999,1,129.990005,109.190002,34.939999,COMPLETE,07-01-2015,Standard Class
3,3,5,DEBIT,6,4,11318,Caguas,Puerto Rico,Mary,Henry,Consumer,PR,3047 Silent Embers Maze,Fan Shop,LATAM,South America,Risaralda,Dos Quebradas,Colombia,01-01-2015,957,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.980011,51.000000,1,299.980011,248.979996,109.550003,COMPLETE,07-01-2015,Standard Class
4,4,5,DEBIT,6,4,11318,Caguas,Puerto Rico,Mary,Henry,Consumer,PR,3047 Silent Embers Maze,Fan Shop,LATAM,South America,Risaralda,Dos Quebradas,Colombia,01-01-2015,957,Camping & Hiking,Diamondback Women's Serene Classic Comfort Bi,299.980011,54.000000,1,299.980011,245.979996,92.239998,COMPLETE,07-01-2015,Standard Class

# **Export files**

In [13]:
df.to_excel(r'/content/drive/MyDrive/UIT-Learning/TERM6/OLAP/ĐỒ ÁN OLAP/Dataset/Smart Supply Chain/final_data.xlsx', encoding="utf-8")
df.to_csv(r'/content/drive/MyDrive/UIT-Learning/TERM6/OLAP/ĐỒ ÁN OLAP/Dataset/Smart Supply Chain/final_data.csv', encoding="utf-8")